version: '3'
services:
  informix-server:
      image: "ibmcom/informix-developer-database"
      container_name: "server"
      hostname: "server"
      environment:
          LICENSE: 'accept'
          SIZE:    'small'
          RUN_FILE_POST_INIT: timeseries_generic.sh
      ports:
         - 27018:27018
         - 9088:9088
  informix-client:
      image: "ibmcom/informix-developer-sandbox"
      container_name: "client"
      hostname: "client"
      environment:
          LICENSE: 'accept'
      ports:
         - 9001:9001



